### ISSUE TITLE
迁移博客请注意标注出处

### ISSUE THREAD

**Issue by zhukunpenglinyutong** [Jiarui-Zeng/Ainz#1]
你好，我个人非常鼓励笔记整理和学习讨论，但是建议，这么大规模迁移我的博客内容，还是需要备注一下的，或者征询一下我的同意。

**Comment by Jiarui-Zeng** [comment]
很抱歉，对你造成了困扰，
最初clone项目下来，是因为看了你的搭建静态博客教程

之前的想法是，试着部署，能成功后在加你微信好友（之前看的教程有看到微信二维码）征询你的同意，在原有的分类条目下对内容下进行修改（主要是前端速查部分，这块内容吸引我，但是内容虽然多，却不能在上面添加自己平时积累的笔记，所以就趴了打算做个自用的博客笔记），用于重新构建被自己搁置已久的旧博客项目。

但是，完成部署后，到加你好友那步我犹豫了，在想要不要现在就加你好友，最后还是想着在我正式开始更新博客前再加（毕竟就博客被搁置了有一年，加你好友后被发现还是没去更新，我怕自己尴尬……）

以上就是事情经过，我真的没有半点恶意，待你收到我的回复后，过段时间我就会删除这个项目（大概是过个几小时）

还有想说的就是，你的博客做的真的非常好，当时就向好几个朋友安利了，工作中也常来查找（是去自己部署好的……，但是还没有在平台上发布过链接，就我和一个朋友知道我部署后的地址，所以才拖了这么久没取征询同意也还觉得问题不大）最后就是我还是会持续关注你的博客的，望常更新

**Comment by Jiarui-Zeng** [comment]
很抱歉，对你造成了困扰，
最初clone项目下来，是因为看了你的搭建静态博客教程


之前的想法是，试着部署，能成功后在加你微信好友（之前看的教程有看到微信二维码）征询你的同意，在原有的分类条目下对内容下进行修改（主要是前端速查部分，这块内容吸引我，但是内容虽然多，却不能在上面添加自己平时积累的笔记，所以就趴了打算做个自用的博客笔记），用于重新构建被自己搁置已久的旧博客项目。


但是，完成部署后，到加你好友那步我犹豫了，在想要不要现在就加你好友，最后还是想着在我正式开始更新博客前再加（毕竟就博客被搁置了有一年，加你好友后被发现还是没去更新，我怕自己尴尬……）


以上就是事情经过，我真的没有半点恶意，待你收到我的回复后，过段时间我就会删除这个项目（大概是过个几小时）


还有想说的就是，你的博客做的真的非常好，当时就向好几个朋友安利了，工作中也常来查找（是去自己部署好的……，但是还没有在平台上发布过链接，就我和一个朋友知道我部署后的地址，所以才拖了这么久没取征询同意也还觉得问题不大）最后就是我还是会持续关注你的博客的，望常更新







------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"朱昆鹏"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月8日(星期三) 中午12:55
收件人:&nbsp;"Jiarui-Zeng/Ainz"<Ainz@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Jiarui-Zeng/Ainz] 迁移博客请注意标注出处 (#1)




你好，我个人非常鼓励笔记整理和学习讨论，但是建议，这么大规模迁移我的博客内容，还是需要备注一下的，或者征询一下我的同意。
